name: JMeter Tests

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Which endpoint to test?"
        required: true
        default: "all"
        type: choice
        options:
          - fast
          - slow
          - unstable
          - all

      test_type:
        description: "Which test file to run?"
        required: true
        default: "load"
        type: choice
        options:
          - load
          - func

jobs:

  fast:
    if: ${{ github.event.inputs.endpoint == 'fast' || github.event.inputs.endpoint == 'all' }}
    runs-on: ubuntu-latest
    name: Run JMeter (fast)
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
      - run: ENDPOINT=fast TEST_FILE=${{ github.event.inputs.test_type }}.jmx docker compose run --rm jmeter
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-fast
          path: jmeter/tests/results/

  slow:
    if: ${{ github.event.inputs.endpoint == 'slow' || github.event.inputs.endpoint == 'all' }}
    runs-on: ubuntu-latest
    name: Run JMeter (slow)
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
      - run: ENDPOINT=slow TEST_FILE=${{ github.event.inputs.test_type }}.jmx docker compose run --rm jmeter
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-slow
          path: jmeter/tests/results/

  unstable:
    if: ${{ github.event.inputs.endpoint == 'unstable' || github.event.inputs.endpoint == 'all' }}
    runs-on: ubuntu-latest
    name: Run JMeter (unstable)
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
      - run: ENDPOINT=unstable TEST_FILE=${{ github.event.inputs.test_type }}.jmx docker compose run --rm jmeter
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-unstable
          path: jmeter/tests/results/
